In [1]:
import numpy as np

array = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

scalarValue = 3
result = array + scalarValue

print(result)

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [2]:
import numpy as np

arrayOne = np.array([2, 3, 4])
arrayTwo = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

result = arrayOne[:, np.newaxis] * arrayTwo

print(result)

[[ 2  4  6]
 [12 15 18]
 [28 32 36]]
