In [1]:
import numpy as np

arrayOne = np.array([1, 2, 3, 4, 5])
arrayTwo = np.array([6, 7, 8, 9, 10])

addition = arrayOne + arrayTwo

subtraction = arrayOne - arrayTwo

multiplication = arrayOne * arrayTwo

division = arrayOne / arrayTwo

print("Addition:", addition)
print("Subtraction:", subtraction)
print("Multiplication:", multiplication)
print("Division:", division)

Addition: [ 7  9 11 13 15]
Subtraction: [-5 -5 -5 -5 -5]
Multiplication: [ 6 14 24 36 50]
Division: [0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [2]:
import numpy as np

array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

mean = np.mean(array)
median = np.median(array)
standardDeviation = np.std(array)

print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", standardDeviation)

Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143


In [3]:
import numpy as np

array = np.arange(12)

reshapedArray = array.reshape(3, 4)
print(reshapedArray)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
