In [1]:
import numpy as np

array = np.arange(1, 11)
print(array)

[ 1  2  3  4  5  6  7  8  9 10]


In [2]:
import numpy as np

array = np.random.rand(3, 4)
print(array)

[[0.46718738 0.11815909 0.51525756 0.6929378 ]
 [0.47585799 0.81651721 0.88761197 0.07534473]
 [0.08871056 0.14637587 0.67035402 0.38384271]]


In [3]:
import numpy as np

array = np.zeros((2, 3, 4))
print(array)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
